### ISSUE TITLE
关于在不同环境中启动出错的问题

### ISSUE THREAD

**Issue by 4sin30** [a6678696/BookManageSystem#2]
博主你好，我在另一台电脑上启动图书管理系统，报出如下错误，而在另一台电脑中启动正常，请问这可能是什么情况导致的呢？谢谢？
![image](https://user-images.githubusercontent.com/58653636/168081327-7c183303-5f23-4ea6-a4a6-91fdb3e11bd6.png)

**Comment by a6678696** [comment]
你的这个问题我也不方便解决（环境问题我不负责解决，只解决系统的BUG），你直接去百度解决办法吧，我找到一篇博客，你去试试行不行，链接为：[点这里跳转](https://www.cnblogs.com/appium/p/11213181.html)
